### ISSUE TITLE
Allow specifying hours for only one day

### ISSUE THREAD

**Issue by Jokab** [yykamei/block-merge-based-on-time#1075]
Hi!

I have been looking for this kind of setting in Github, and it seem this action solves my use case except for one thing. I want to block merges only between the hours 09:30 - 12:00 on Tuedays. This seems to not be possible. This is what I have tried:

```
name: Block Merge Based on Time
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: "*/30 * * * *"

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/block-merge-based-on-time@v2
        with:
          timezone: Europe/Stockholm
          after: "09:30 on Tuesday"
          before: "12:00 on Tuesday"
          base-branches: "main"
```

Gives the error:
`Error: Unhandled error: Error: "after" requires at least basic hour like "16:30"`

The issue is that I don't want to provide a basic hour or a default for every day – Tuesdays is the only day I want this to run on. Unless I'm doing something wrong, would this be possible to add?

Thanks!
