### ISSUE TITLE
Cron job is not running on opened PRs

### ISSUE THREAD

**Issue by carmilso** [yykamei/block-merge-based-on-time#1123]
I'm trying to run the Github Action so it should be run (or I would expect it to be running) every 30 minutes on opened PRs. The problem is that it only runs when I push a commit to the branch with the PR opened, but it seems that the cron has no effect because it just run once. 

This is the code I am using for the Github Action:

```
name: Block Merge Based on Time
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  schedule:
    - cron: "*/30 * * * *"

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - uses: yykamei/block-merge-based-on-time@main
        with:
          timezone: Europe/Madrid
          after: "12:40 on Tuesday"
          before: "12:50"
          base-branches: "prod"
          prohibited-days-dates: "Sunday"
```

From what I understood reading the README, this action should run every 30 minutes on opened PR to block or unblock the merge on them.

What could be the problem? Thanks!
