### ISSUE TITLE
Output a state for using in other steps when PR was blocked

### ISSUE THREAD

**Issue by LucasMMota** [yykamei/block-merge-based-on-time#1341]
For example, I want to comment in PR when the PR is blocked only.
Is there something implemented already for outputting the `yykamei/block-merge-based-on-time` state? Otherwise it'd be nice to have, like: `steps.block_check.outputs.is_pr_blocked`

```yaml
      - uses: yykamei/block-merge-based-on-time@main
        id: block_check
        if: steps.check_label.outputs.is_full_refresh == 'true'
        with:
          timezone: America/Sao_Paulo
          base-branches: "(default)"
          commit-status-description-while-blocking: "PRs that need Full-Refresh must be merged on Monday or Thursday"
          prohibited-days-dates: "Sunday, Tuesday, Wednesday, Friday, Saturday"

      - name: Comment in PR
        if: steps.block_check.outputs.is_pr_blocked == 'true'
        uses: "actions/github-script@v6"
        with:
          script: |
            const comment = `:warning: **PR is blocked** `;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            })
```
