### ISSUE TITLE
Handle Merge Queue Type Events

### ISSUE THREAD

**Issue by dluftspring** [yykamei/block-merge-based-on-time#1362]
👋 I'm trying to build a workflow where merges are handled automatically but only during certain hours of the day. Your action works exactly as advertised but when used in conjuction with the merge queue event type it throws the following error

```bash
Error: Unhandled error: Error: This action does not support the event "merge_group"
```

In my workflow definition I have

```yaml
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  merge_group:
    branches: [ main ]
```
