### ISSUE TITLE
Feature: Option to provide user-maintained `holidays.json` style file

### ISSUE THREAD

**Issue by seanorama** [yykamei/block-merge-based-on-time#2345]
Would it be possible to specify a user-provided JSON in addition to `src/holidays.json`?

Or another approach to the scenario below.

Why:
1. I have a large number of blackout windows.
2. I've thought to add them to `src/holidays.json` but that would cause conflicts when pulling updates.
3. And putting dozens of days into `prohibited-days-dates:` will be painful to manage/review, and likely not work.

**Comment by yykamei** [comment]
@seanorama 

Thank you so much for opening this issue! That's a really interesting idea, and we appreciate you bringing it up! 👍

While this GitHub Action doesn't currently have a built-in feature to use a user-provided JSON, I agree that implementing this is definitely a possibility we can explore!

Looking at the code, the `src/holidays.json` file is read by this function.

https://github.com/yykamei/block-merge-based-on-time/blob/ce001a5c40910460105fb84661d503a05da8a777/src/inputs.ts#L117-L123

This suggests we could potentially use an alternative `holidays` file instead of the default one.

We imagine an ideal GitHub workflow for using a user-provided JSON could look something like this:

```yaml
    steps:
      - uses: yykamei/block-merge-based-on-time@main
        id: block
        with:
          timezone: Europe/London
          after: '18:00'
          before: '09:00'
          custom-holidays-path: .github/workflows/my-holidays.json
```

What do you think?
